export const WEAVE_BAR_HEIGHT_PX = 26;
export const WEAVE_BAR_WIDTH_PX = 3;
export const WEAVE_BAR_SPACE_BETWEEN_PX = 1;
export const AUDIO_TRANSCRIBE_COLOR_PRIMARY = '#4CA3F0';
export const AUDIO_TRANSCRIBE_COLOR_SECONDARY = '#8868E9';
